services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - "8000:80"    # Laravel API
            - "8080:8080"  # Reverb WebSocket
        volumes:
            - .:/var/www
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=messageapp
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - REVERB_APP_ID=802751
            - REVERB_APP_KEY=hbrebdgtltg89tldyqme
            - REVERB_APP_SECRET=rrhixcnx5xgaxkypabhx
            - REVERB_HOST="localhost"
            - REVERB_PORT=8080
            - REVERB_SCHEME=http
        networks:
            - app-network

    frontend:
        build:
            context: ./realtime-chat-app
            dockerfile: Dockerfile
        ports:
            - "4200:80"  # Angular frontend
        networks:
            - app-network

    db:
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=messageapp
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
